# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    resource_class: large
    docker:
      # specify the version you desire here
      - image: circleci/node:lts
        environment:

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo/website
    environment:
      TZ: "America/Los_Angeles"

    steps:
      - checkout:
          path: ~/repo

      - run:
          name: Pulling Sub-modules
          command: pushd .. ; git submodule init ;  git submodule update ; popd
      - run:
          name: Pulling Sub-modules1 
          command: pushd ../COVID-19/ ; git checkout master; git pull; popd
      - run:
          name: Pulling Sub-modules2
          command: pushd  ../coronavirus-data/ ;  git checkout master; git pull; popd

      # Install exact dependencies
      - run:
          name: Upgrade NPM
          command: npmv=$(echo $(npm -v) | head -c 1); if [ "$npmv" -lt "6" ]; then npm i -g npm; else echo "Node.js Docker Team finally decided to include npm v6+ in latest image; you can remove this script now"; fi
      - run:
          name: Install Dependencies
          command: npm ci 
      # Set up Firebase
      - run:
          name: Create Firebase Config
          command: echo $FIREBASE_CONFIG > src/firebaseConfig.json

      # Build data
      - run:
          name: Build
          command: npm run data

      # Build
      - run:
          name: Build
          command: npm run build

      # Deploy
      - run:
          name: Deploy to Firebase
          command: ./node_modules/.bin/firebase deploy --token $FIREBASE_TOKEN --only hosting
  dataupdate:
    docker:
      # specify the version you desire here
      - image: circleci/node:lts
        environment:
    working_directory: ~/repo/website
    environment:
      TZ: "America/Los_Angeles"
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Pulling Sub-modules
          command: pushd .. ; git submodule init ;  git submodule update ; popd
      # Install exact dependencies
      - run:
          name: Upgrade NPM
          command: npmv=$(echo $(npm -v) | head -c 1); if [ "$npmv" -lt "6" ]; then npm i -g npm; else echo "Node.js Docker Team finally decided to include npm v6+ in latest image; you can remove this script now"; fi
      - run:
          name: Install Dependencies
          command: npm ci 
      # Set up Firebase
      - run:
          name: Create Firebase Config
          command: echo $FIREBASE_CONFIG > src/firebaseConfig.json
      - run:
          name: configure Git
          command: git config --global user.email "xhuang@gmail.com"; git config --global user.name "Xun Wilson Huang (from CircleCI)"
      - run:
          name: Refresh data
          command: sh refreshdata.sh
      - run:
          name: CA hospitalization data
          command: pushd countydata/CA-06; sh fetch.sh; popd
      - run:
          name: Pull main data
          command: node refresh.js

workflows:
  version: 2
  # commit-workflow:
  # jobs:
  # - build 
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0,20,40 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - dataupdate

