# This is a basic workflow to help you get started with Actions

name: Data Pull (refresh)

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch

on:
  schedule:
  - cron: "10,30,50 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: America/Los_Angeles
      - name: firebaseConfig
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: cd website; echo "${FIREBASE_CONFIG}" > src/firebaseConfig.json;  cd ..
      - run: cd website; npm ci  ; cd ..
      - run: cd website; git config --global user.email "xhuang@gmail.com"; git config --global user.name "Xun Wilson Huang (from GitHub Action )"; cd ..
      - run: cd website; sh -x refreshdata.sh ; cd .. 
      - run: cd website; pushd countydata/CA-06; sh fetch.sh; popd; cd .. 
      - run: cd website; node refresh.js ; cd .. 
